
// This file has been generated by the GUI designer. Do not modify.
namespace Diplom
{
	public partial class SettingsWindows
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.VBox vbox11;

		private global::Gtk.SpinButton tempBegin;

		private global::Gtk.SpinButton tempEnd;

		private global::Gtk.SpinButton tempStep;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.VBox vbox13;

		private global::Gtk.SpinButton timeSp;

		private global::Gtk.SpinButton timeSp1;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entryMSD;

		private global::Gtk.VBox vbox4;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label17;

		private global::Gtk.ComboBoxEntry comboPort;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Diplom.SettingsWindows
			this.Name = "Diplom.SettingsWindows";
			this.Title = global::Mono.Unix.Catalog.GetString("Настройки");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Internal child Diplom.SettingsWindows.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Homogeneous = true;
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Начальная");
			this.vbox10.Add(this.label11);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label11]));
			w2.Position = 0;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Конечная");
			this.vbox10.Add(this.label12);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label12]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Шаг");
			this.vbox10.Add(this.label13);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label13]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox4.Add(this.vbox10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox10]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Homogeneous = true;
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.tempBegin = new global::Gtk.SpinButton(-200D, 200D, 1D);
			this.tempBegin.CanFocus = true;
			this.tempBegin.Name = "tempBegin";
			this.tempBegin.Adjustment.PageIncrement = 10D;
			this.tempBegin.ClimbRate = 1D;
			this.tempBegin.Numeric = true;
			this.tempBegin.Value = 11D;
			this.vbox11.Add(this.tempBegin);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.tempBegin]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.tempEnd = new global::Gtk.SpinButton(-200D, 200D, 1D);
			this.tempEnd.CanFocus = true;
			this.tempEnd.Name = "tempEnd";
			this.tempEnd.Adjustment.PageIncrement = 10D;
			this.tempEnd.ClimbRate = 1D;
			this.tempEnd.Numeric = true;
			this.vbox11.Add(this.tempEnd);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.tempEnd]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.tempStep = new global::Gtk.SpinButton(-10D, 100D, 1D);
			this.tempStep.CanFocus = true;
			this.tempStep.Name = "tempStep";
			this.tempStep.Adjustment.PageIncrement = 10D;
			this.tempStep.Adjustment.PageSize = -10D;
			this.tempStep.ClimbRate = 1D;
			this.tempStep.Numeric = true;
			this.vbox11.Add(this.tempStep);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.tempStep]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox4.Add(this.vbox11);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox11]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.GtkAlignment2.Add(this.hbox4);
			this.frame1.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Температура, &#176;С</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.hbox3.Add(this.frame1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame1]));
			w12.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Homogeneous = true;
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Измерений");
			this.vbox12.Add(this.label14);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label14]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Период");
			this.vbox12.Add(this.label15);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label15]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox5.Add(this.vbox12);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox12]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Homogeneous = true;
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.timeSp = new global::Gtk.SpinButton(0D, 999999999D, 1D);
			this.timeSp.CanFocus = true;
			this.timeSp.Name = "timeSp";
			this.timeSp.Adjustment.PageIncrement = 10D;
			this.timeSp.ClimbRate = 1D;
			this.timeSp.Numeric = true;
			this.timeSp.Value = 28D;
			this.vbox13.Add(this.timeSp);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.timeSp]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.timeSp1 = new global::Gtk.SpinButton(0D, 999999999D, 1D);
			this.timeSp1.CanFocus = true;
			this.timeSp1.Name = "timeSp1";
			this.timeSp1.Adjustment.PageIncrement = 10D;
			this.timeSp1.ClimbRate = 1D;
			this.timeSp1.Numeric = true;
			this.timeSp1.Value = 15D;
			this.vbox13.Add(this.timeSp1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.timeSp1]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox5.Add(this.vbox13);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox13]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.GtkAlignment3.Add(this.hbox5);
			this.frame2.Add(this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.Xalign = 0F;
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Ожидание, сек</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.hbox3.Add(this.frame2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame2]));
			w21.Position = 1;
			w1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(w1[this.hbox3]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("СКО");
			this.hbox6.Add(this.label6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryMSD = new global::Gtk.Entry();
			this.entryMSD.CanFocus = true;
			this.entryMSD.Name = "entryMSD";
			this.entryMSD.IsEditable = true;
			this.entryMSD.InvisibleChar = '●';
			this.hbox6.Add(this.entryMSD);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryMSD]));
			w24.Position = 1;
			w1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w1[this.hbox6]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Homogeneous = true;
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("COM - порт");
			this.hbox2.Add(this.label17);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label17]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboPort = global::Gtk.ComboBoxEntry.NewText();
			this.comboPort.Name = "comboPort";
			this.hbox2.Add(this.comboPort);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboPort]));
			w27.Position = 1;
			this.vbox9.Add(this.hbox2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox2]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(5));
			this.vbox4.Add(this.vbox9);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox9]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			w1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(w1[this.vbox4]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			// Internal child Diplom.SettingsWindows.ActionArea
			global::Gtk.HButtonBox w31 = this.ActionArea;
			w31.Name = "dialog1_ActionArea";
			w31.Spacing = 10;
			w31.BorderWidth = ((uint)(5));
			w31.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31[this.buttonCancel]));
			w32.Expand = false;
			w32.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31[this.buttonOk]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 269;
			this.Show();
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
