
// This file has been generated by the GUI designer. Do not modify.
namespace Diplom
{
	public partial class Form
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Diplom.Form
			this.Name = "Diplom.Form";
			this.Title = global::Mono.Unix.Catalog.GetString ("Form");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
